apiVersion: v2
name: fr3d-blog
description: My personal blog

type: application

# This is the chart version. This version number should be incremented each time you make changes
version: 0.1.0
icon: "https://gohugo.io/images/hugo-logo-wide.svg"
appVersion: "1.0.0"
