apiVersion: v1
kind: Service
metadata:
  name: {{ include "fr3d-blog.fullname" . }}
  labels:
    {{- include "fr3d-blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http-proxy
  selector:
    {{- include "fr3d-blog.selectorLabels" . | nindent 4 }}
